package com.nikolaswidad.oaseapp.model

object FakeNewsDataSource {
    val dummyNews = listOf(
        NewsUi(
            1,
            "Jokowi Pastikan Ibu Kota Baru Tawarkan Konsep Kota Smart Metropolis",
            "R.drawable.news_pro",
            "KOMPAS",
            "7 Hours Ago",
            "Real",
            88,
            "Positive",
            77,
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        ),
        NewsUi(
            2,
            "Ki Hajar Dewantara",
            "https://raw.githubusercontent.com/dicodingacademy/assets/main/android_compose_academy/pahlawan/2.jpg",
            "KOMPAS",
            "7 Hours Ago",
            "Real",
            50,
            "Positive",
            30,
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        ),
        NewsUi(
            3,
            "R.M. Surjopranoto",
            "https://raw.githubusercontent.com/dicodingacademy/assets/main/android_compose_academy/pahlawan/3.jpg",
            "KOMPAS",
            "7 Hours Ago",
            "Real",
            88,
            "Positive",
            77,
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        ),
        NewsUi(
            4,
            "Mohammad Hoesni Thamrin",
            "https://raw.githubusercontent.com/dicodingacademy/assets/main/android_compose_academy/pahlawan/4.jpg",
            "KOMPAS",
            "7 Hours Ago",
            "Real",
            88,
            "Positive",
            77,
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        ),
        NewsUi(
            5,
            "KH. Samanhudi",
            "https://raw.githubusercontent.com/dicodingacademy/assets/main/android_compose_academy/pahlawan/5.jpg",
            "KOMPAS",
            "7 Hours Ago",
            "Real",
            88,
            "Positive",
            77,
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        ),
        NewsUi(
            6,
            "H.O.S. Cokroaminoto",
            "https://raw.githubusercontent.com/dicodingacademy/assets/main/android_compose_academy/pahlawan/6.jpg",
            "KOMPAS",
            "7 Hours Ago",
            "Real",
            88,
            "Positive",
            77,
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        ),
        NewsUi(
            7,
            "Danudirja Setiabudi",
            "https://raw.githubusercontent.com/dicodingacademy/assets/main/android_compose_academy/pahlawan/7.jpg",
            "KOMPAS",
            "7 Hours Ago",
            "Real",
            88,
            "Positive",
            77,
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        ),
        NewsUi(
            8,
            "Si Singamangaradja XII",
            "https://raw.githubusercontent.com/dicodingacademy/assets/main/android_compose_academy/pahlawan/8.jpg",
            "KOMPAS",
            "7 Hours Ago",
            "Real",
            88,
            "Positive",
            77,
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        ),
    )
}